### ISSUE TITLE
ET5 - fine-tuning 관련 오류

### ISSUE THREAD

**Issue by seuly1203** [O-per/cakd3_Project3#28]
```
DATA_DIR = '/content/drive/MyDrive/211130_test'
PRETRAINED_MODEL_DIR = '/content/drive/MyDrive/cakd3_3차프로젝트_2조/Datasets/ETRI_ET5/pytorch_model.bin'
OUTPUT_DIR = '/content/drive/MyDrive/ET5_test/output'

!CUDA_VISIBLE_DEVICES=0 python seq2seq_finetune_t5_ynat.py \
--do_train --do_eval --predict_with_generate \
--model_name_or_path PRETRAINED_MODEL_DIR \
--data_dir DATA_DIR/ynat-v1.1 \
--output_dir OUTPUT_DIR \
--overwrite_output_dir \
--save_steps 100000 \
--per_device_train_batch_size 16 \
--gradient_accumulation_steps 1 \
--num_train_epochs 1.0
```
코드 돌렸을때 다음과 같은 에러 메세지

```
11/30/2021 10:39:43 - WARNING - __main__ -   Process rank: -1, device: cuda:0, n_gpu: 1, distributed training: False, 16-bits training: False
11/30/2021 10:39:43 - INFO - __main__ -   Training/evaluation parameters Seq2SeqTrainingArguments(output_dir='OUTPUT_DIR', overwrite_output_dir=True, do_train=True, do_eval=True, do_predict=False, evaluation_strategy=<EvaluationStrategy.NO: 'no'>, prediction_loss_only=False, per_device_train_batch_size=16, per_device_eval_batch_size=8, per_gpu_train_batch_size=None, per_gpu_eval_batch_size=None, gradient_accumulation_steps=1, eval_accumulation_steps=None, learning_rate=5e-05, weight_decay=0.0, adam_beta1=0.9, adam_beta2=0.999, adam_epsilon=1e-08, max_grad_norm=1.0, num_train_epochs=1.0, max_steps=-1, lr_scheduler_type=<SchedulerType.LINEAR: 'linear'>, warmup_steps=0, logging_dir='runs/Nov30_10-39-43_b3a2f3e3466e', logging_first_step=False, logging_steps=500, save_steps=100000, save_total_limit=None, no_cuda=False, seed=42, fp16=False, fp16_opt_level='O1', fp16_backend='auto', local_rank=-1, tpu_num_cores=None, tpu_metrics_debug=False, debug=False, dataloader_drop_last=False, eval_steps=500, dataloader_num_workers=0, past_index=-1, run_name='OUTPUT_DIR', disable_tqdm=False, remove_unused_columns=True, label_names=None, load_best_model_at_end=False, metric_for_best_model=None, greater_is_better=None, ignore_data_skip=False, sharded_ddp=False, deepspeed=None, label_smoothing_factor=0.0, adafactor=False, group_by_length=False, report_to=['tensorboard'], ddp_find_unused_parameters=None, dataloader_pin_memory=True, label_smoothing=0.0, sortish_sampler=False, predict_with_generate=True, encoder_layerdrop=None, decoder_layerdrop=None, dropout=None, attention_dropout=None, lr_scheduler='linear')
[ERROR|configuration_utils.py:430] 2021-11-30 10:39:43,364 >> 404 Client Error: Not Found for url: https://huggingface.co/PRETRAINED_MODEL_DIR/resolve/main/config.json
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/transformers/configuration_utils.py", line 424, in get_config_dict
    use_auth_token=use_auth_token,
  File "/usr/local/lib/python3.7/dist-packages/transformers/file_utils.py", line 1086, in cached_path
    local_files_only=local_files_only,
  File "/usr/local/lib/python3.7/dist-packages/transformers/file_utils.py", line 1216, in get_from_cache
    r.raise_for_status()
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/PRETRAINED_MODEL_DIR/resolve/main/config.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "seq2seq_finetune_t5_ynat.py", line 379, in <module>
    main()
  File "seq2seq_finetune_t5_ynat.py", line 199, in main
    cache_dir=model_args.cache_dir,
  File "/usr/local/lib/python3.7/dist-packages/transformers/models/auto/configuration_auto.py", line 368, in from_pretrained
    config_dict, _ = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/transformers/configuration_utils.py", line 436, in get_config_dict
    raise EnvironmentError(msg)
OSError: Can't load config for 'PRETRAINED_MODEL_DIR'. Make sure that:

- 'PRETRAINED_MODEL_DIR' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'PRETRAINED_MODEL_DIR' is the correct path to a directory containing a config.json file
```

**Comment by seuly1203** [comment]
https://huggingface.co/PRETRAINED_MODEL_DIR/resolve/main/config.json
쳤을때
'PRETRAINED_MODEL_DIR' 에 't5-base' 넣으면 ETRI_ET5 > config.json 결과 나와야함
- 이걸 허깅페이스에 어떻게 저장해야할지?
- 아니면 https://huggingface.co/PRETRAINED_MODEL_DIR/resolve/main/config.json 이거 자체를 config.json 파일 path로 바꿔야할 것 같습니다

**Comment by seuly1203** [comment]
file_utils.py 추가 및 수정 사항 되는지 확인

```
    # 원본 #
    #return HUGGINGFACE_CO_PREFIX.format(model_id=model_id, revision=revision, filename=filename)

    # 21/12/01 수정/추가
    try:
      r = HUGGINGFACE_CO_PREFIX.format(model_id=model_id, revision=revision, filename=filename)
      return r
    except:
      local_pretrained_path = PRETRAINED_MODEL_DIR
      return local_pretrained_path
    #
```

**Comment by seuly1203** [comment]
아래꺼 안되서 다시
```
    # 원본 #
    #return HUGGINGFACE_CO_PREFIX.format(model_id=model_id, revision=revision, filename=filename)

    # 21/12/01 수정/추가
    local_pretrained_path = PRETRAINED_MODEL_DIR
    return local_pretrained_path
    #
```

> file_utils.py 추가 및 수정 사항 되는지 확인
> 
> ```
>     # 원본 #
>     #return HUGGINGFACE_CO_PREFIX.format(model_id=model_id, revision=revision, filename=filename)
> 
>     # 21/12/01 수정/추가
>     try:
>       r = HUGGINGFACE_CO_PREFIX.format(model_id=model_id, revision=revision, filename=filename)
>       return r
>     except:
>       local_pretrained_path = PRETRAINED_MODEL_DIR
>       return local_pretrained_path
>     #
> ```

**Comment by seuly1203** [comment]
"PRETRAINED_MODEL_DIR" 부분에 pytorch_model.bin / config.json / spiece.model / tokenizer_config.json 이 포함 된 폴더를 입력해야함
