### ISSUE TITLE
ET5- BookSummary 미세조정 (seq2seq_finetuen_t5_ynat.py 기반 코드 수정)

### ISSUE THREAD

**Issue by seuly1203** [O-per/cakd3_Project3#34]
오류메세지:
```
Traceback (most recent call last):
  File "seq2seq_finetune_t5_bs.py", line 388, in <module>
    main()
  File "seq2seq_finetune_t5_bs.py", line 273, in main
    if training_args.do_train
  File "/content/drive/My Drive/test_et5_finetune/finetune-t5-booksummary/seq2seq_dataset_et5.py", line 37, in __init__
    (src_texts, tgt_texts) = processor.get_seq2seq_examples(filename=self.data_file)
  File "/content/drive/My Drive/test_et5_finetune/finetune-t5-booksummary/seq2seq_data_processor.py", line 32, in get_seq2seq_examples
    examples = self.get_examples(filename, set_type)
  File "/content/drive/My Drive/test_et5_finetune/finetune-t5-booksummary/seq2seq_data_processor.py", line 57, in get_examples
    examples = self.create_examples(lines, set_type)
  File "/content/drive/My Drive/test_et5_finetune/finetune-t5-booksummary/seq2seq_data_processor.py", line 69, in create_examples
    passage_id = line["passage_id"] # PCY_201708291123519121_11
TypeError: list indices must be integers or slices, not str
```

문제되는 부분 코드:
```
    def create_examples(self, lines, set_type):
        """Creates examples for the training and dev sets."""
        examples = []
        for (i, line) in tqdm(enumerate(lines), desc="#####\t Create examples ... "):
            if i == 0:
                continue
            #################
            passage_id = line["passage_id"] # PCY_201708291123519121_11
            passage = line["passage"]
            summary = line["summary"]
            ################
            examples.append(
                BookSummary_Example(passage_id=passage_id, passage=passage, summary=summary))
    
        return examples
```

**Comment by seuly1203** [comment]
https://careerkarma.com/blog/python-typeerror-list-indices-must-be-integers-or-slices-not-str/

**Comment by seuly1203** [comment]
```
for (i, line) in tqdm(enumerate(lines), desc="#####\t Create examples ... "):
            if i == 0:
                continue
            #################
            passage_id = line["passage_id"] # PCY_201708291123519121_11
            passage = line["passage"]
            summary = line["summary"]
```

이 코드 자체에는 에러가 없음(따로 프린트했을때 에러 없이 잘 나옴)
그런데 py 파일 실행시 안돌아가서
len사용해서 시도해보겠습니다

**Comment by seuly1203** [comment]
type(lines) : list
type(lines[0]) : dict -> 딕셔너리 형태여서 key를 사용한 인덱싱 가능 -> line[0]['passage_id'] == 'PCY_201806050513469141_124'

```
for (i, line) in tqdm(enumerate(lines), desc="#####\t Create examples ... "):
            if i == 0:
                continue
            #################
            passage_id = line["passage_id"] # PCY_201708291123519121_11
            passage = line["passage"]
            summary = line["summary"]
```
에서 i (인덱스), line (딕셔너리) 인데 왜 안될까요?

**Comment by seuly1203** [comment]
![image](https://user-images.githubusercontent.com/86218998/144976447-bdb92375-0d8e-424e-a934-ce220c048594.png)

- 문제: lines 각각의 element는 하나의 딕셔너리 형태였는데 lines[13891]에 여러 개의 딕셔너리 들어가있어서 위 코드 실행시typeerror 발생

**Comment by seuly1203** [comment]
train.json, val.json 파일 수정으로 해결
