### ISSUE TITLE
ET5- BookSummary 데이터 기반 미세조정/예측 중 오류

### ISSUE THREAD

**Issue by seuly1203** [O-per/cakd3_Project3#35]
오류메세지:
```
Traceback (most recent call last):
  File "seq2seq_finetune_t5_bs.py", line 388, in <module>
    main()
  File "seq2seq_finetune_t5_bs.py", line 359, in main
    test_output = trainer.predict(test_dataset=test_dataset, metric_key_prefix="test")
  File "/usr/local/lib/python3.7/dist-packages/transformers/trainer.py", line 1569, in predict
    output.metrics.update(speed_metrics(metric_key_prefix, start_time, len(test_dataset)))
  File "/usr/local/lib/python3.7/dist-packages/transformers/trainer_utils.py", line 221, in speed_metrics
    samples_per_second = 1 / (runtime / num_samples)
ZeroDivisionError: float division by zero
```

num_samples == 0 인 상태여서 생기는 문제인 것 같은데 어디서 num_samples를 받는지/생성되는지 모르겠음

```
Traceback (most recent call last):
  File "seq2seq_finetune_t5_bs.py", line 388, in <module>
    main()
  File "seq2seq_finetune_t5_bs.py", line 325, in main
    model_path=model_args.model_name_or_path if os.path.isdir(model_args.model_name_or_path) else None
  File "/usr/local/lib/python3.7/dist-packages/transformers/trainer.py", line 742, in train
    train_dataloader = self.get_train_dataloader()
  File "/usr/local/lib/python3.7/dist-packages/transformers/trainer.py", line 482, in get_train_dataloader
    train_sampler = self._get_train_sampler()
  File "/content/drive/MyDrive/test_et5_finetune/finetune-t5-booksummary/seq2seq/seq2seq_trainer.py", line 158, in _get_train_sampler
    if self.args.local_rank == -1
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/sampler.py", line 104, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0
```

**Comment by seuly1203** [comment]
https://github.com/facebookresearch/detr/issues/196

**Comment by seuly1203** [comment]
from '/usr/local/lib/python3.7/dist-packages/torch/utils/data/sampler.py'
```
class RandomSampler(Sampler[int]):
    r"""Samples elements randomly. If without replacement, then sample from a shuffled dataset.
    If with replacement, then user can specify :attr:`num_samples` to draw.

    Args:
        data_source (Dataset): dataset to sample from
        replacement (bool): samples are drawn on-demand with replacement if ``True``, default=``False``
        num_samples (int): number of samples to draw, default=`len(dataset)`. This argument
            is supposed to be specified only when `replacement` is ``True``.
        generator (Generator): Generator used in sampling.
    """
    data_source: Sized
    replacement: bool

    def __init__(self, data_source: Sized, replacement: bool = False,
                 num_samples: Optional[int] = None, generator=None) -> None:
        self.data_source = data_source
        self.replacement = replacement
        self._num_samples = num_samples
        self.generator = generator

        if not isinstance(self.replacement, bool):
            raise TypeError("replacement should be a boolean value, but got "
                            "replacement={}".format(self.replacement))

        if self._num_samples is not None and not replacement:
            raise ValueError("With replacement=False, num_samples should not be specified, "
                             "since a random permute will be performed.")

        if not isinstance(self.num_samples, int) or self.num_samples <= 0:
            raise ValueError("num_samples should be a positive integer "
                             "value, but got num_samples={}".format(self.num_samples))

    @property
    def num_samples(self) -> int:
        # dataset size might change at runtime
        if self._num_samples is None:
            return len(self.data_source)
        return self._num_samples
```

**Comment by seuly1203** [comment]
from '/content/drive/MyDrive/test_et5_finetune/finetune-t5-booksummary/seq2seq/seq2seq_trainer.py'

```
    def _get_train_sampler(self) -> Optional[torch.utils.data.sampler.Sampler]:
        if isinstance(self.train_dataset, torch.utils.data.IterableDataset):
            return None
        elif is_torch_tpu_available():
            return get_tpu_sampler(self.train_dataset)
        else:
            if self.args.sortish_sampler:
                self.train_dataset.make_sortish_sampler(
                    self.args.per_device_train_batch_size,
                    distributed=(self.args.parallel_mode == ParallelMode.DISTRIBUTED),
                )

            return (
                RandomSampler(self.train_dataset)
                if self.args.local_rank == -1
                else DistributedSampler(self.train_dataset)
            )
```

**Comment by seuly1203** [comment]
from 'trainer.py'

```
    def get_train_dataloader(self) -> DataLoader:
        """
        Returns the training :class:`~torch.utils.data.DataLoader`.

        Will use no sampler if :obj:`self.train_dataset` does not implement :obj:`__len__`, a random sampler (adapted
        to distributed training if necessary) otherwise.

        Subclass and override this method if you want to inject some custom behavior.
        """
        if self.train_dataset is None:
            raise ValueError("Trainer: training requires a train_dataset.")
        train_sampler = self._get_train_sampler()

        return DataLoader(
            self.train_dataset,
            batch_size=self.args.train_batch_size,
            sampler=train_sampler,
            collate_fn=self.data_collator,
            drop_last=self.args.dataloader_drop_last,
            num_workers=self.args.dataloader_num_workers,
            pin_memory=self.args.dataloader_pin_memory,
        )
```

**Comment by seuly1203** [comment]
제대로 작동될 때 메세지

```
[INFO|modeling_utils.py:1152] 2021-12-07 09:54:48,155 >> All the weights of T5ForConditionalGeneration were initialized from the model checkpoint at /content/drive/MyDrive/cakd3_3차프로젝트_2조/Datasets/ETRI_ET5.
If your task is similar to the task the model of the checkpoint was trained on, you can already use T5ForConditionalGeneration for predictions without further training.
#####	 Reading an input file ...	 /content/drive/MyDrive/ET5_test/ynat-v1.1/train.json
#####	 Create examples ... : 45678it [00:00, 645019.02it/s]
#####	 Get source and target texts ... : 100% 45677/45677 [00:00<00:00, 1518116.17it/s]
#####	 Reading an input file ...	 /content/drive/MyDrive/ET5_test/ynat-v1.1/val.json
#####	 Create examples ... : 9107it [00:00, 765190.14it/s]
#####	 Get source and target texts ... : 100% 9106/9106 [00:00<00:00, 1560567.63it/s]
12/07/2021 09:54:50 - INFO - __main__ -   *** Train ***
/usr/local/lib/python3.7/dist-packages/transformers/trainer.py:705: FutureWarning: `model_path` is deprecated and will be removed in a future version. Use `resume_from_checkpoint` instead.
  FutureWarning,
[INFO|trainer.py:724] 2021-12-07 09:54:50,205 >> Loading model from /content/drive/MyDrive/cakd3_3차프로젝트_2조/Datasets/ETRI_ET5).
[INFO|configuration_utils.py:447] 2021-12-07 09:54:50,207 >> loading configuration file /content/drive/MyDrive/cakd3_3차프로젝트_2조/Datasets/ETRI_ET5/config.json
[INFO|configuration_utils.py:485] 2021-12-07 09:54:50,208 >> Model config T5Config {
  "architectures": [
    "T5ForConditionalGeneration"
  ],
  "d_ff": 3072,
  "d_kv": 64,
  "d_model": 768,
  "decoder_start_token_id": 0,
  "dropout_rate": 0.1,
  "eos_token_id": 1,
  "feed_forward_proj": "gated-gelu",
  "initializer_factor": 1.0,
  "is_encoder_decoder": true,
  "layer_norm_epsilon": 1e-06,
  "model_type": "t5",
  "num_decoder_layers": 12,
  "num_heads": 12,
  "num_layers": 12,
  "pad_token_id": 0,
  "relative_attention_num_buckets": 32,
  "tie_word_embeddings": false,
  "tokenizer_class": "T5Tokenizer",
  "transformers_version": "4.3.2",
  "use_cache": true,
  "vocab_size": 45100
}

[INFO|modeling_utils.py:1025] 2021-12-07 09:54:50,209 >> loading weights file /content/drive/MyDrive/cakd3_3차프로젝트_2조/Datasets/ETRI_ET5/pytorch_model.bin
[INFO|modeling_utils.py:1143] 2021-12-07 09:54:57,876 >> All model checkpoint weights were used when initializing T5ForConditionalGeneration.

[INFO|modeling_utils.py:1152] 2021-12-07 09:54:57,876 >> All the weights of T5ForConditionalGeneration were initialized from the model checkpoint at /content/drive/MyDrive/cakd3_3차프로젝트_2조/Datasets/ETRI_ET5.
If your task is similar to the task the model of the checkpoint was trained on, you can already use T5ForConditionalGeneration for predictions without further training.
[INFO|trainer.py:837] 2021-12-07 09:54:57,885 >> ***** Running training *****
[INFO|trainer.py:838] 2021-12-07 09:54:57,885 >>   Num examples = 45676
[INFO|trainer.py:839] 2021-12-07 09:54:57,885 >>   Num Epochs = 1
[INFO|trainer.py:840] 2021-12-07 09:54:57,885 >>   Instantaneous batch size per device = 16
[INFO|trainer.py:841] 2021-12-07 09:54:57,885 >>   Total train batch size (w. parallel, distributed & accumulation) = 16
[INFO|trainer.py:842] 2021-12-07 09:54:57,885 >>   Gradient Accumulation steps = 1
[INFO|trainer.py:843] 2021-12-07 09:54:57,885 >>   Total optimization steps = 2855
```

**Comment by seuly1203** [comment]
```
[INFO|modeling_utils.py:1152] 2021-12-07 08:08:06,600 >> All the weights of T5ForConditionalGeneration were initialized from the model checkpoint at /content/drive/MyDrive/1_et5_download_mask_iii_base.
If your task is similar to the task the model of the checkpoint was trained on, you can already use T5ForConditionalGeneration for predictions without further training.
#####	 Reading an input file ...	 /content/drive/MyDrive/test_et5_finetune/ynat-v1.1/train.json
#####	 Create examples ... 
#####	 Get source and target texts ... : 100% 1/1 [00:00<00:00, 10330.80it/s]
#####	 Reading an input file ...	 /content/drive/MyDrive/test_et5_finetune/ynat-v1.1/val.json
#####	 Create examples ... 
#####	 Get source and target texts ... : 100% 1/1 [00:00<00:00, 12228.29it/s]
12/07/2021 08:08:07 - INFO - __main__ -   *** Train ***
/usr/local/lib/python3.7/dist-packages/transformers/trainer.py:705: FutureWarning: `model_path` is deprecated and will be removed in a future version. Use `resume_from_checkpoint` instead.
  FutureWarning,
[INFO|trainer.py:724] 2021-12-07 08:08:07,510 >> Loading model from /content/drive/MyDrive/1_et5_download_mask_iii_base).
[INFO|configuration_utils.py:447] 2021-12-07 08:08:07,511 >> loading configuration file /content/drive/MyDrive/1_et5_download_mask_iii_base/config.json
[INFO|configuration_utils.py:485] 2021-12-07 08:08:07,511 >> Model config T5Config {
  "architectures": [
    "T5ForConditionalGeneration"
  ],
  "d_ff": 3072,
  "d_kv": 64,
  "d_model": 768,
  "decoder_start_token_id": 0,
  "dropout_rate": 0.1,
  "eos_token_id": 1,
  "feed_forward_proj": "gated-gelu",
  "initializer_factor": 1.0,
  "is_encoder_decoder": true,
  "layer_norm_epsilon": 1e-06,
  "model_type": "t5",
  "num_decoder_layers": 12,
  "num_heads": 12,
  "num_layers": 12,
  "pad_token_id": 0,
  "relative_attention_num_buckets": 32,
  "tie_word_embeddings": false,
  "tokenizer_class": "T5Tokenizer",
  "transformers_version": "4.3.2",
  "use_cache": true,
  "vocab_size": 45100
}

[INFO|modeling_utils.py:1025] 2021-12-07 08:08:07,512 >> loading weights file /content/drive/MyDrive/1_et5_download_mask_iii_base/pytorch_model.bin
[INFO|modeling_utils.py:1143] 2021-12-07 08:08:15,264 >> All model checkpoint weights were used when initializing T5ForConditionalGeneration.

[INFO|modeling_utils.py:1152] 2021-12-07 08:08:15,265 >> All the weights of T5ForConditionalGeneration were initialized from the model checkpoint at /content/drive/MyDrive/1_et5_download_mask_iii_base.
If your task is similar to the task the model of the checkpoint was trained on, you can already use T5ForConditionalGeneration for predictions without further training.
Traceback (most recent call last):
  File "seq2seq_finetune_t5_bs.py", line 388, in <module>
    main()
  File "seq2seq_finetune_t5_bs.py", line 325, in main
    model_path=model_args.model_name_or_path if os.path.isdir(model_args.model_name_or_path) else None
  File "/usr/local/lib/python3.7/dist-packages/transformers/trainer.py", line 742, in train
    train_dataloader = self.get_train_dataloader()
  File "/usr/local/lib/python3.7/dist-packages/transformers/trainer.py", line 482, in get_train_dataloader
    train_sampler = self._get_train_sampler()
  File "/content/drive/MyDrive/test_et5_finetune/finetune-t5-booksummary/seq2seq/seq2seq_trainer.py", line 158, in _get_train_sampler
    if self.args.local_rank == -1
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/sampler.py", line 104, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0
```

**Comment by seuly1203** [comment]
https://stackoverflow.com/questions/61568462/python-typing-what-does-typevara-b-covariant-true-mean

**Comment by seuly1203** [comment]
" Map-style datasets

A map-style dataset is one that implements the __getitem__() and __len__() protocols, and represents a map from (possibly non-integral) indices/keys to data samples.

For example, such a dataset, when accessed with dataset[idx], could read the idx-th image and its corresponding label from a folder on the disk. "

인덱싱 에러에서 계속 되는 문제인가?
